ShowTeaching = true
ShowNotes = true
ShowDev = true
BookLogo = "fablearn.png"
CustomCSS = ["css/book_custom.css"]
ExcludeTypesFromMenu = ["teaching", "notes"]
Teacher = "a member of the teaching team"
LookAction = "ğŸ‘€"
CodeAction = "ğŸ’»"
WriteAction = "âœï¸"
